---
title: "Big Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```


```{r big_read, cache = TRUE}
# The real data does not have the same columns as the demo data. Very annoying!
# Note you can use the n_max argument to read_csv() to just read in the first
# 100 or so rows, thereby quickly getting back the message about the column
# types. Then, we use this new listing of types. Use cache = TRUE so that you
# don't have to repeat long calculations every time you reknit the document.

x <- read_csv("~/data/census/censoc_dmf_v2/censoc_dmf_v2.csv",
                   col_types = cols(HISTID = col_character(),
                                    byear = col_double(),
                                    bmonth = col_double(),
                                    dyear = col_double(),
                                    dmonth = col_double(),
                                    death_age = col_double(),
                                    link_abe_exact_conservative = col_double(),
                                    weight = col_double(),
                                    weight_conservative = col_double()))
```

create 1% sample of data

```{r}

# It's preferable to first work on a small sample of the data and make sure
# everything works.

small <- x %>% 
  slice_sample(prop = 0.01) 
  
```

create bar plot of dmonth

```{r}

# trying a plot on the small sample 
small %>% 
  select(dyear, dmonth) %>% 
  group_by(dmonth, dyear) %>% 
  count() %>% 
  pivot_wider(names_from = dmonth,
              names_prefix = "dmonth_",
              values_from = n) %>% 
  mutate(jan_july_ratio = dmonth_1/dmonth_7 ) %>%  ggplot(mapping = aes(x = dyear,
                       y = jan_july_ratio)) +
  geom_point() +
  geom_smooth(method = "lm",
              formula = y ~ x)
```

```{r}
# trying the plot on the big data

x %>% 
  select(dyear, dmonth) %>% 
  group_by(dmonth, dyear) %>% 
  count() %>% 
  pivot_wider(names_from = dmonth,
              names_prefix = "dmonth_",
              values_from = n) %>% 
  mutate(jan_july_ratio = dmonth_1/dmonth_7 ) %>%  ggplot(mapping = aes(x = dyear,
                       y = jan_july_ratio)) +
  geom_point() +
  geom_smooth(method = "lm",
              formula = y ~ x)
```

